package pid_codec;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author FREE
 */
public class CarregarView extends javax.swing.JFrame {
    private boolean modoInvalido = false;
    private String decodedPath;
    private static JFileChooser fcBuffer = null;
    private File fileBuffer = null;
    
    private ArrayList<Long> historicoDeTempos = new ArrayList<>();
    private long[] tempos = new long[2];
    /**
     * Creates new form CarregarView
     */
    public CarregarView(){
        initComponents();
        String path = CarregarView.class.getProtectionDomain().getCodeSource().getLocation().getPath();
        centralizarJanela(this);
        drawPanel.setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btCarregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAvisos = new javax.swing.JTextArea();
        lbMsg = new javax.swing.JLabel();
        btAbrirVideo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        drawPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5), "CarregarCena"));

        btCarregar.setText("Comprimir");
        btCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarregarActionPerformed(evt);
            }
        });

        taAvisos.setColumns(20);
        taAvisos.setRows(5);
        jScrollPane1.setViewportView(taAvisos);

        lbMsg.setText("Mensagem : ");

        btAbrirVideo.setText("AbrirVideo");
        btAbrirVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirVideoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMsg)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCarregar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAbrirVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMsg)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCarregar)
                    .addComponent(btAbrirVideo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        drawPanel.setBackground(new java.awt.Color(153, 153, 153));
        drawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        drawPanel.setPreferredSize(new java.awt.Dimension(2000, 2000));

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(drawPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarregarActionPerformed
        // TODO add your handling code here:
        lbMsg.setText("Abrindo imagem.....");
        this.setVisible(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("BMP","bmp","arquivo bmp");
        if (fcBuffer==null)
        {
            fcBuffer = new JFileChooser();
        }
        fcBuffer.setFileFilter(filter);
        
        int returnVal = fcBuffer.showOpenDialog(this);
        
        try{
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {
                File file = fcBuffer.getSelectedFile();
                fileBuffer = file;
                String nomeCompleto = file.getName();
                String basicoNome = nomeCompleto.substring(0,9);
                String extensao = nomeCompleto.substring(nomeCompleto.length()-4, nomeCompleto.length());
                int id = 0;
                File dir = file.getParentFile();
                while (true){ // Procura para ver quantos arquivos tem
                    String nomeProcurado = dir.getPath()+"//"+basicoNome+util.retornarStringPorNumero(id)+extensao;
                    File proximaFile = new File(nomeProcurado);
                    if (proximaFile.exists()){
                        id = id+1;
                    }else{
                        id = id-1;
                        break;
                    }
                }
                // (File diretorio,String baseNome,String extensao,int ultimoID,File nameOut)
                File fileOut = new File(dir,"comprimido.hue");
                VideoWriter.write(dir, basicoNome, extensao, id, fileOut);
                /*
                JFrame frame = new JFrame();
                imagemPanel imgP = new imagemPanel(file);
                frame.add(imgP);
                frame.pack();
                frame.setVisible(true);
                */
            }
            else
            {
                lbMsg.setText("Cancelado!");
                //this.setVisible(true);
            }
        }
        catch( Exception e)
        {
            //this.setVisible(true);
            e.printStackTrace();
            lbMsg.setText("Erro!");
            taAvisos.setText("Erro e = " + e.getMessage());
        }
        System.out.println("end");
    }//GEN-LAST:event_btCarregarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    private void btAbrirVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirVideoActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        lbMsg.setText("Abrindo video..");
        this.setVisible(true);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("HUE","hue","arquivo hue");
        if (fcBuffer==null)
        {
            fcBuffer = new JFileChooser();
        }
        fcBuffer.setFileFilter(filter);
        
        int returnVal = fcBuffer.showOpenDialog(this);
        
        try{
            if (returnVal == JFileChooser.APPROVE_OPTION)
            {
                File file = fcBuffer.getSelectedFile();
                VideoReader vr = new VideoReader(file);
                
                
                Timer timer;
                tempos[0] = System.nanoTime();
                ActionListener listener = new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent event){
                        //System.out.println("next frame!");
                        PTimer tempo = new PTimer("tempo exibicao");
                        tempo.startTimer();
                        Timer t = (Timer)event.getSource();
                        boolean ret = vr.nextFrame();
                        tempo.endTimer();
                        long elapsed = tempo.getElapsed();
                        if (ret){
                            historicoDeTempos.add(elapsed);
                        }
                        if (!ret  || elapsed > 33333333){
                            t.restart();
                            //System.out.println("estouro");
                        }else{
                            t.restart();
                            //int delay = (int) ((33333333-elapsed)/1E6);
                            //t.setDelay(delay);
                        }
                        if (vr.hasVideoEnded()){
                            tempos[1] = System.nanoTime();
                            for (Long l : historicoDeTempos){
                                System.out.println("Tempo : " + (l/1E9+0.00) + "s");
                            }
                            System.out.println("Tempo total : " + ((tempos[1]-tempos[0])/(1E9+0.00)));
                            ((Timer)event.getSource()).stop();
                        }
                        //System.out.println("tempo :  " + tempo);
                    }
                };
                
                timer = new Timer(33, listener);
                timer.setRepeats(true);
                timer.start();
                
                //t1.run();
                /*
                JFrame frame = new JFrame();
                imagemPanel imgP = new imagemPanel(file);
                frame.add(imgP);
                frame.pack();
                frame.setVisible(true);
                */
            }
            else
            {
                lbMsg.setText("Cancelado!");
                //this.setVisible(true);
            }
        }
        catch( Exception e)
        {
            //this.setVisible(true);
            e.printStackTrace();
            lbMsg.setText("Erro!");
            taAvisos.setText("Erro e = " + e.getMessage());
        }
        System.out.println("end");
    }//GEN-LAST:event_btAbrirVideoActionPerformed
    public static void centralizarJanela(JFrame janela)
    {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        janela.setLocation(dim.width/2-janela.getSize().width/2, dim.height/2-janela.getSize().height/2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarregarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CarregarView().setVisible(true);
            }
        });
    }
    
    private void aoFechar()
    {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirVideo;
    private javax.swing.JButton btCarregar;
    private javax.swing.JPanel drawPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JTextArea taAvisos;
    // End of variables declaration//GEN-END:variables

}

