/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pid_codec;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author FREE
 */
public class imagemPanel extends javax.swing.JPanel {
    private BufferedImage buffer = null;
    /**
     * Creates new form imagemPanel
     */
    
    public imagemPanel(Imagem imagem){
        initComponents();
        if (imagem!=null){
            changeImage(imagem);
        }
    }
    
    public void changeImage(Imagem img){
            PTimer inicio = new PTimer("changeImage tempo");
            inicio.startTimer();
            try{
                byte[] pixels = img.getBytes();

                int imagemWidth = img.getWidth();
                int imagemHeight = img.getHeight();

                if (buffer==null){
                    buffer = new BufferedImage(imagemWidth,imagemHeight,BufferedImage.TYPE_INT_ARGB);
                }
                
                byte[] aux = new byte[3];
                for (int i=0;i<imagemHeight;i++){
                        for (int j=0;j<imagemWidth;j++){
                            System.arraycopy(pixels, (i*imagemWidth+j)*3 , aux, 0, 3);
                            buffer.setRGB(j, (imagemHeight-1-i), Cor.getValorInt(aux));
                        }
                    }
                this.setPreferredSize(new Dimension(buffer.getWidth(),buffer.getHeight()));
                this.setSize(this.getPreferredSize());
                this.repaint();
                }
            catch(Exception e){
                System.out.println("Erro imagemPanel");
                e.printStackTrace();
            }finally{
                inicio.endTimer();
                System.out.println(img.testPrint());
                //System.out.println(inicio);
            }
    }
    
    @Override
    public void paint(Graphics g)
    {
        if (!(buffer==null)){
            //System.out.println("DRAWING");
            g.drawImage(buffer, 0, 0, this);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
